# Generated by Django 4.1.7 on 2023-03-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='image',
            field=models.ImageField(default=1, upload_to='images/stat/'),
            preserve_default=False,
        ),
    ]
