# Generated by Django 4.1.7 on 2023-03-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='education',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.education'),
            preserve_default=False,
        ),
    ]
